name: Teste Cypress

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Cypress-run:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout no código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm run test
