name: Teste Cypress

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout no código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install
          
      - name: Configurar locale do sistema para pt-BR
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-pt
          sudo locale-gen pt_BR.UTF-8
          sudo update-locale LANG=pt_BR.UTF-8
          export LANG=pt_BR.UTF-8

      - name: Executar testes
        run: npm run test
